# Documentation used in this: 
#https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers
name: backend ci pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  implement-ci-pipeline-backend:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Setup
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: run backend tst
        working-directory: ./backend
        run: npm run test

      - name: Lintering
        working-directory: ./backend
        run: npm run lint

      - name: audit
        working-directory: ./backend
        run: npm audit --audit-level=critical