name: frontend ci pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  implement-ci-pipeline-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Setup
        working-directory: ./frontend
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: run frontend tst
        working-directory: ./frontend
        run: npm run test

      - name: Lintering
        working-directory: ./frontend
        run: npm run lint

      - name: audit
        working-directory: ./frontend
        run: npm audit --audit-level=critical