name: frontend ci pipeline

on:
  push:
    branches:
     - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # reference source: https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags
  #pull_request:
   # branches:
    #  - main
  workflow_dispatch:

jobs:
  implement-ci-pipeline-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: Setup
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: run frontend tst
        working-directory: ./frontend
        run: npm run test

      - name: Lintering
        working-directory: ./frontend
        run: npm run lint

      - name: audit
        working-directory: ./frontend
        run: npm audit --audit-level=critical

  implement-cd-pipeline-frontend:
    
    needs: implement-ci-pipeline-frontend
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONT}} # Reference source: https://dev.to/jtorbett23/render-github-actions-2b92
        run: |
          curl "$deploy_url"
